default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hope_school_development

test:
  <<: *default
  database: hope_school_test

production:
  <<: *default
  database: hope_school_production
