default: &default
  adapter: postgresql
  encoding: unicode
  # Adding defaults here prevents the KeyError crash
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  database: <%= ENV.fetch("POSTGRES_DB", "hope_school_development") %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "password") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default

test:
  <<: *default
  database: hope_school_test

production:
  <<: *default
  # In production, Rails will prioritize DATABASE_URL if it exists
  url: <%= ENV['DATABASE_URL'] %>